### ISSUE TITLE
How can I set it to be with one Thumb\Handle? (not lower and upper)

### ISSUE THREAD

**Issue by AlonRom** [AndreiMisiukevich/RangeSlider#3]

**Comment by AndreiMisiukevich** [comment]
Try to set LowerValueLabelStyle

Set IsVisible to false.

**Comment by AndreiMisiukevich** [comment]
I guess you cannot do it now with this control
Do you actually need it? You can use Xamarin.Forms Slider for achieving that

**Comment by AlonRom** [comment]
> I guess you cannot do it now with this control
> Do you actually need it? You can use Xamarin.Forms Slider for achieving that

I want your package because you have round corners and a border color to the handle.

**Comment by AndreiMisiukevich** [comment]
Try the next approach

```xaml
        <Style x:Key="CustomLowerValueLabelStyle" TargetType="Label">
            <Setter Property="IsVisible" Value="False"/> 
        </Style>
```

Then

```xaml
LowerThumbSize="0"
LowerValueLabelStyle="{StaticResource CustomLowerValueLabelStyle}"
```

**Comment by AndreiMisiukevich** [comment]
And let me know if it works for you :)

**Comment by AlonRom** [comment]
> And let me know if it works for you :)

thanks, I achieved it like this:
  <range:RangeSlider
                    Margin="32,0,32,30"
                    HorizontalOptions="Fill"
                    InputTransparent="False"
                    IsVisible="{Binding IsTempZoneCircle}"
                    LowerThumbBorderColor="White"
                    LowerThumbColor="{StaticResource StrongCyan}"
                    LowerThumbSize="30"
                    LowerValue="{Binding CircleRadius, Mode=TwoWay}"
                    MaximumValue="{Binding RadiusMaximumMultiplier, Mode=TwoWay}"
                    MinimumValue="{Binding RadiusMinimumMultiplier, Mode=TwoWay}"
                    ThumbSize="0"
                    TrackColor="{StaticResource DarkGrayishBlue}"
                    TrackHighlightColor="{StaticResource DarkGrayishBlue}"
                    TrackRadius="-1"
                    TrackSize="6"
                    UpperValue="{Binding RadiusMaximumMultiplier, Mode=TwoWay}"
                    ValueLabelStringFormat=""
                    VerticalOptions="End" />

But, I want to maintain only one bindable value to the handle.
which one to use from all of these:

 MaximumValue="10"
 MinimumValue="-10"
 LowerValue="-10"
 UpperValue="10"

**Comment by AndreiMisiukevich** [comment]
MinimumValue manages Minimum possible value (0 by default)
MaximumValue manages Maximum possible value (1.0 by default)

LowerValue is a current Lower value
UpperValue is a current Upper value


I hope it makes sense

**Comment by AlonRom** [comment]
> MinimumValue manages Minimum possible value (0 by default)
> MaximumValue manages Maximum possible value (1.0 by default)
> 
> LowerValue is a current Lower value
> UpperValue is a current Upper value
> 
> I hope it makes sense

yes, it is, but which one to use? I only want 1 :)

**Comment by AndreiMisiukevich** [comment]
> > MinimumValue manages Minimum possible value (0 by default)
> > MaximumValue manages Maximum possible value (1.0 by default)
> > LowerValue is a current Lower value
> > UpperValue is a current Upper value
> > I hope it makes sense
> 
> yes, it is, but which one to use? I only want 1 :)



> Try the next approach
> 
> ```
>         <Style x:Key="CustomLowerValueLabelStyle" TargetType="Label">
>             <Setter Property="IsVisible" Value="False"/> 
>         </Style>
> ```
> 
> Then
> 
> ```
> LowerThumbSize="0"
> LowerValueLabelStyle="{StaticResource CustomLowerValueLabelStyle}"
> ```


Well, if you do it like this, then you should observe UpperValue

**Comment by AlonRom** [comment]
> > > MinimumValue manages Minimum possible value (0 by default)
> > > MaximumValue manages Maximum possible value (1.0 by default)
> > > LowerValue is a current Lower value
> > > UpperValue is a current Upper value
> > > I hope it makes sense
> > 
> > 
> > yes, it is, but which one to use? I only want 1 :)
> 
> > Try the next approach
> > ```
> >         <Style x:Key="CustomLowerValueLabelStyle" TargetType="Label">
> >             <Setter Property="IsVisible" Value="False"/> 
> >         </Style>
> > ```
> > 
> > 
> > Then
> > ```
> > LowerThumbSize="0"
> > LowerValueLabelStyle="{StaticResource CustomLowerValueLabelStyle}"
> > ```
> 
> Well, if you do it like this, then you should observe UpperValue

And not even "LowerValue" ?

**Comment by AndreiMisiukevich** [comment]
Lower value must be set the same with Minimum Value

**Comment by AlonRom** [comment]
> Lower value must be set the same with Minimum Value

ok, cool. and how do I hide the value label above?

**Comment by AndreiMisiukevich** [comment]
```xaml
<Style x:Key="CustomLowerValueLabelStyle" TargetType="Label">
    <Setter Property="IsVisible" Value="False"/> 
</Style>
```

**Comment by AlonRom** [comment]
> ```
> <Style x:Key="CustomLowerValueLabelStyle" TargetType="Label">
>     <Setter Property="IsVisible" Value="False"/> 
> </Style>
> ```

Great, I end up wit this:

   <Style x:Key="CustomLowerValueLabelStyle" TargetType="Label">
            <Setter Property="IsVisible" Value="False" />
        </Style>

   <range:RangeSlider
                    Margin="32,0,32,30"
                    HorizontalOptions="Fill"
                    InputTransparent="False"
                    IsVisible="{Binding IsTempZoneCircle}"
                    LowerThumbSize="0"
                    LowerValue="{Binding RadiusMinimumMultiplier, Mode=TwoWay}"
                    LowerValueLabelStyle="{StaticResource CustomLowerValueLabelStyle}"
                    UpperValueLabelStyle="{StaticResource CustomLowerValueLabelStyle}"
                    MaximumValue="{Binding RadiusMaximumMultiplier, Mode=TwoWay}"
                    MinimumValue="{Binding RadiusMinimumMultiplier, Mode=TwoWay}"
                    ThumbBorderColor="White"
                    ThumbColor="{StaticResource StrongCyan}"
                    ThumbSize="30"
                    TrackColor="{StaticResource DarkGrayishBlue}"
                    TrackHighlightColor="{StaticResource DarkGrayishBlue}"
                    TrackRadius="-1"
                    TrackSize="6"
                    UpperValue="{Binding CircleRadius, Mode=TwoWay}"
                    VerticalOptions="End" />

Looks and behaves ok, I hope that's what you meant.
Great nuget!
